name: json_rpc_2
version: 3.0.1
description: >-
  Utilities to write a client or server using the JSON-RPC 2.0 spec.
homepage: https://github.com/dart-lang/json_rpc_2
environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  stack_trace: ^1.10.0
  stream_channel: ^2.1.0

dev_dependencies:
  test: ^1.20.1
  pedantic: ^1.11.0
  web_socket_channel: ^2.1.0
